### ISSUE TITLE
Progress Tracking 

### ISSUE THREAD

**Issue by Aux** [Akitaux/Twitch#1]
#### Helix
- [x] Analytics 2/2
- [x] Bits 1/1
- [x] Clips 2/2
- [x] Entitlements 3/3
- [x] Games 2/2
- [x] Streams 4/4
- [ ] Subscriptions 0/2
- [ ] Tags 0/3
- [ ] Users 0/6
- [ ] Videos 0/1
- [ ] Webhooks 0/1
#### Kraken
- [ ] Bits 0/?
- [ ] Channel Feed 0/?
- [ ] Channels 0/?
- [ ] Chat 0/?
- [ ] Clips 0/?
- [ ] Collections 0/?
- [ ] Communities 0/?
- [ ] Games 0/?
- [ ] Ingests 0/?
- [ ] Search 0/?
- [ ] Streams 0/?
- [ ] Teams 0/?
- [ ] Users 0/?
- [ ] Videos 0/?
#### Identity
- [ ] 4/7? Endpoints Implemented
#### Chat
- [x] Basic connection and payload handling
- [ ] Create event models and handlers
- [ ] Implement a stateless serializer
- [ ] Better method of authentication 
#### PubSub
- [ ] Basic connection and payload handling
- [ ] Create event models and handlers
